### ISSUE TITLE
Mixup augmentation bug, yielding wrong targets

### ISSUE THREAD

**Issue by Adamusen** [WongKinYiu/YOLO#105]
## Describe the bug
The in "yolo/tools/data_augmentation.py/MixUp" implemented mixup augmentation yields wrong targets, as it multiplies the boxes tensors, containing target class IDs and target box coordinates, with a random float value, shown in the code snippet below:

```
        # Calculate the mixup lambda parameter
        lam = np.random.beta(self.alpha, self.alpha) if self.alpha > 0 else 0.5

        # Mix images
        image1, image2 = TF.to_tensor(image), TF.to_tensor(image2)
        mixed_image = lam * image1 + (1 - lam) * image2

        # Mix bounding boxes
        mixed_boxes = torch.cat([lam * boxes, (1 - lam) * boxes2])
```

## Expected behavior
Simply merge the targets coming from the pair of images that are mixed.

## Proposed solution
Replacing the last two lines in the code snippet above to the following would fix the issue:

```
        # Merge bounding boxes
        merged_boxes = torch.cat((boxes, boxes2))
```

**Comment by nkinnaird** [comment]
Just wanted to comment and say thank you for finding this!

**Comment by Adamusen** [comment]
Hey,

opened a new pull request for the DATASET branch with the changes as requested by maintainer:
https://github.com/WongKinYiu/YOLO/pull/110

closed the previous one as duplicate.
