### ISSUE TITLE
AP approaching zero when training with custom dataset from CVAT

### ISSUE THREAD

**Issue by jackdaw213** [WongKinYiu/YOLO#109]
**Issue Description**
I created a custom dataset using CVAT and exported it in the COCO 1.0 format, which provided a JSON annotation file containing only bounding boxes, without segmentation. This has led to a few issues:

1. Using a mock dataset with segmentation removed causes the Average Precision (AP) to drop nearly to zero.
![image](https://github.com/user-attachments/assets/440e0bd5-73dd-46dd-93b6-70510ba3017b)
2. When using my custom dataset, the results are even worse, as the code cannot detect any valid bounding boxes. 
![image](https://github.com/user-attachments/assets/0bfc2fc8-93d1-49ee-9ef0-8d1737627a8c)

My question is: why are bounding boxes extracted from segmentation data rather than directly using them from the annotation file? Also, how should I go about addressing this issue?

**Comment by ramonhollands** [comment]
The dataset_utils.py code seems to assume that the bbox element in the annotation file represents a bounding box in segmentation style, defined by eight points: (x1, y1, x2, y1, x2, y2, x1, y2).

```
if "segmentation" in anno:
    seg_list = [item for sublist in anno["segmentation"] for item in sublist]
elif "bbox" in anno:
    seg_list = anno["bbox"]
```

In contrast, the COCO format represents bounding boxes as [x, y, width, height]

**Comment by henrytsui000** [comment]
> The dataset_utils.py code seems to assume that the bbox element in the annotation file represents a bounding box in segmentation style, defined by eight points: (x1, y1, x2, y1, x2, y2, x1, y2).
> 
> ```
> if "segmentation" in anno:
>     seg_list = [item for sublist in anno["segmentation"] for item in sublist]
> elif "bbox" in anno:
>     seg_list = anno["bbox"]
> ```
> 
> In contrast, the COCO format represents bounding boxes as [x, y, width, height]

Actually, this issue exists because I initially used segmentation to extract bounding boxes and never tried using the bounding boxes directly—this is indeed a bug. 
I can fix it in the next update, or if anyone is able to make a PR, that would be great!

**Comment by ramonhollands** [comment]
Yes I'll create a pull request 👍

**Comment by ramonhollands** [comment]
I create a pull request (https://github.com/WongKinYiu/YOLO/pull/112)

**Comment by jackdaw213** [comment]
#116 should fix the problem
