### ISSUE TITLE
Load weights from other implementations of YOLOv9

### ISSUE THREAD

**Issue by virgile-fsr** [WongKinYiu/YOLO#111]
Hello,

I know the training pipeline is still WIP. However I wanted to know if it was possible to load custom weights for YOLOv9 that were trained with another repo (ultralytics for example) and then use it for inference?

**Comment by henrytsui000** [comment]
Hi,

I haven’t tried YOLOv9 myself or looked into its model architecture, but I believe the overall architecture might be similar or the same. You could try implementing a simple weight transfer process by renaming the weight_name in the `OrderedDict`. I think this is feasible and shouldn’t be too difficult.

However, please note that you’ll need to check the license if you’re using weights from Ultralytics or any other source that’s not under the MIT License.
