### ISSUE TITLE
Access issue in git clone command

### ISSUE THREAD

**Issue by dsbyprateekg** [WongKinYiu/YOLO#129]
Hi,

I am facing the following issue while installing the code using git command `!git clone git@github.com:WongKinYiu/YOLO.git`

`Cloning into 'YOLO'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by tloki** [comment]
This is kind of a bug in documentation.try:git clone https://github.com/WongKinYiu/YOLO.gitOn 25 Nov 2024, at 10:15, Prateek Gupta ***@***.***> wrote:﻿
Hi,
I am facing the following issue while installing the code using git command !git clone ***@***.***:WongKinYiu/YOLO.git
`Cloning into 'YOLO'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`

**Comment by dsbyprateekg** [comment]
> https://github.com/WongKinYiu/YOLO.gitOn

I tried but still issue there-

![image](https://github.com/user-attachments/assets/f94ef386-dfed-4b6d-8108-1e4163c82e08)

**Comment by dsbyprateekg** [comment]
@tloki Yes I corrected that.

Can you please also help me to resolve this issue while starting a custom training?

When I run the command `!python yolo/lazy.py task=train task.data.batch_size=8 model=v9-c dataset=lego device=cuda` I got only this one liner in output log file: `:chart_with_upwards_trend: Enable Model EMA
`
