### ISSUE TITLE
Training YOLOv9m: Extremely Long Training Duration (~80 Days)

### ISSUE THREAD

**Issue by ProfessorHT** [WongKinYiu/YOLO#138]
Hello,

First of all, thank you for this amazing project!

I am trying to train the YOLOv9m model with the following configuration:

- Dataset size: ~7000 images (train + val)
- Image size: 1024x1024
- Class: 1
- Epochs: 500
- Batch size: 8
- Hardware: GPU

![Capture](https://github.com/user-attachments/assets/37f4cb87-9603-4d3a-861c-76af898c96b2)
![image](https://github.com/user-attachments/assets/45ea99ee-042f-4031-a755-afe30191cbf0)

However, as you can see in the image, the estimated training time is approximately 80 days. This seems unusually long.

- Is this expected for such a configuration?
- Could there be something wrong with my setup, or are there any optimizations I can apply to reduce the training time?

Also, I would like to monitor the training process using TensorBoard. Could you please guide me on how to launch TensorBoard for this project?

Any insights would be greatly appreciated.

Thank you!

**Comment by Adamusen** [comment]
Hey,

No, these training times are extremely high, usually it should take between a couple dozen hours to a couple of days depending on the dataset and hardware used of course.
My assumption is that you are overflowing your GPU memory, forcing it to use "shared" memory with your system memory. That makes training extremely slow. You should try lowering your batch size (train.yaml) and/or take a smaller network variant (v9-s for example). In addition monitor your GPU memory usage and make sure it does not go full.

Best regards
