### ISSUE TITLE
Error training command of README.md

### ISSUE THREAD

**Issue by chilin0525** [WongKinYiu/YOLO#24]
Hi,

I found the example command of README.md is not correct and got following error when execute to train model.Look like you change train confg ([b5fa3f1](https://github.com/WongKinYiu/yolov9mit/commit/b5fa3f15f944e88cba4962129bd911b15815fe1e)) but forget to update example command of README.

Reproduce and error:
```
$ python lazy.py task=train task.batch_size=8 model=v9-c
Could not override 'task.batch_size'.
To append to your config use +task.batch_size=8
Key 'batch_size' is not in struct
    full_key: task.batch_size
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

And I will create a PR to fix it.

**Comment by henrytsui000** [comment]
Hi,

The README in the next version has been updated, but because CI will be re-run every time I push the main branch, I will update it together later~
```shell
$python yolo/lazy.py task.data.batch_size=8
```

best regards,
Hao-Tang Tsui

**Comment by chilin0525** [comment]
Got it.

**Comment by chilin0525** [comment]
BTW, I think to create issue template just like PR template will help user to search and manage issue better. 😃

**Comment by henrytsui000** [comment]
Hi [Contributor's Name],

I have added the templates for issues in commits bce644c0306518260774dc9c93220c44c57b7494 and fab25903d9a5be5e3ab8450ea12bd807a306f509. Thank you for your suggestion!

Best regards,
[Your Name]
