### ISSUE TITLE
[Feature Suggestion] Stabilize execution environment by fixing PyTorch, CUDA, TensorRT, and ONNX versions

### ISSUE THREAD

**Issue by PINTO0309** [WongKinYiu/YOLO#28]
First, I installed the environment using requirements.txt according to the instructions in the README, and then ran a test inference. However, I encountered a segmentation fault in Conv2D caused by a combination problem of PyTorch v2.3.0 + CUDA 11.8.
- This problem has been reported in a PyTorch issue.
  - [Segmentation fault (core dumped) when using pytorch Conv layers #126963](https://github.com/pytorch/pytorch/issues/126963)

Since we often find that users spend a great deal of time in their environments trying to maintain the YOLOv9-MIT runtime environment due to the lack of fixed versions of PyTorch and other modules, we thought it would be a good idea to fix the runtime environment with a Docker container.

I understand that this repository is in the process of being improved quite frequently, so if it gets in the way of your work, feel free to ignore it, but I would like to issue a pull request for suggestions on creating a Dockerfile environment.

- Verified Fork is located at
  https://github.com/PINTO0309/yolov9mit/tree/feat_dockerfile

- The main points of the proposed improvements are as follows
  - Add build instructions for CPU version of Docker container and CUDA+TensorRT version of Docker container to README
  - Build the container as a general user, not as a privileged user
  - Include TensorRT Execution Provider in onnxruntime-gpu (It will be possible to run TensorRT via onnx)
  - Fix all versions of a minimum set of required packages to a specific version
  - Enables rapid debugging environment from Dockerfile using VSCode's devcontainer, etc.

- Pull request: https://github.com/WongKinYiu/yolov9mit/pull/29/

**Comment by henrytsui000** [comment]
Hi,

Thank you for your suggestion and pull request. I will review the PR after I take a look at Docker!

In the next updates, I plan to provide the suggested versions of each package and separate the requirements for different levels.

Best regards,
Hao-Tang, Tsui

**Comment by josht000** [comment]
@PINTO0309 Do these version combinations in your dockerfile test a distributed GPU training (DDP)? I've noticed that if the pytorch versions are mismatched from what the developer originally intended it will cause issues. 

@henrytsui000 Do you use/test multi gpu training with pytorch 1.12? 

Thanks,

**Comment by PINTO0309** [comment]
>Do these version combinations in your dockerfile test a distributed GPU training (DDP)?

No, I am not. You can rewrite the Dockerfile and rebuild it yourself. In the first place, no one can give a clear reply to your question because the details of what kind of problem will arise have not been shared.
