### ISSUE TITLE
Questions on Yolov9-MIT

### ISSUE THREAD

**Issue by tjasmin111** [WongKinYiu/YOLO#34]
Interesting repo. I notice the notation to predict/train models is totally different from regular YOLO. Is that correct? e.g. we can not call `python yolo detect train dataset=data.yaml device=0,1`. Is it correct?

Also, how does it perform against the original yolov9 in terms of mAP and speed?

**Comment by henrytsui000** [comment]
Q1
Yes and no. The command lines are different. For example:
Inference with a webcam can be done using `python yolo/lazy.py task.data.source=0` or directly running `$yolo task.data.source=0` in the command line. For more argument examples, you can refer to the [HOWTO](https://github.com/WongKinYiu/YOLO/blob/main/docs/HOWTO.md) page. We will provide detailed documentation for the arguments in the future.
For your specific command example, you can use `yolo task=train dataset=data.yaml`. For multiple GPU training, use `torchrun --nproc_per_node=gpu yolo/lazy.py`.

Currently, we only support detection tasks, but more tasks will be implemented in the near future!

This repository is the official implementation of YOLOv9. The theoretical results should be the same as or better than the original YOLOv9 in terms of performance and inference speed. Some functions are still in progress.

**Comment by tjasmin111** [comment]
Thanks. So 2 recommendations:
In the future, maybe we can use the exact arguments used in yolo for better usability?
Maybe we benefit from adding classification task as well.
