### ISSUE TITLE
RepNBottleneck -> RepBottleneck?

### ISSUE THREAD

**Issue by TatsuyaShirakawa** [WongKinYiu/YOLO#49]
Thanks for your great work!

**Issue Description**
I don't fully understand the naming convention, but the current `RepNBottlenck` does not support `repeat_num`. Therefore, I think it would be better to rename it to `RepBottleneck`, similar to `RepConv`.
https://github.com/WongKinYiu/YOLO/blob/ba6baa6c81bf198847d53a95d0fa9902fec69cb2/yolo/model/module.py#L201

**Comment by henrytsui000** [comment]
Hi,

Got it. I think this is a mistake that I didn't catch during the code review of the module pull request. In the upcoming update, I will rename the class as you mentioned above.

Thank you for bringing this to my attention!

Best regards,
Henry Tsui
