### ISSUE TITLE
Different model sizes

### ISSUE THREAD

**Issue by tjasmin111** [WongKinYiu/YOLO#81]
So currently there are 3 model sizes: c, s, e. Do any of them correspond to Yolo's Nano model (yolov8-n)? Any comparisons? I need it to be fast and small.

**Comment by Abdul-Mukit** [comment]
@tjasmin111 you can check out the publication for v9.
https://arxiv.org/abs/2402.13616
The graph is hard to see, but it looks like v9 is better ont all scales.
![image](https://github.com/user-attachments/assets/511ec0f2-4be5-4033-9537-281b4904de4f)
